CHANGELOG.md, addon/components/polaris-icon.js, addon/templates/components/polaris-icon.hbs, tests/integration/components/polaris-icon-test.js, tests/mocks/components/svg-jar.js
Updates `polaris-icon` to match the [v2.0.0 React component](https://github.com/Shopify/polaris/compare/v1.12.4...v2?diff=split#diff-ac192d85916a4a5bf777ae9cb10c1a08) by adding the internal `isColored` class (required for proper icon rendering now), and setting the new `focusable` and `aria-hidden` attributes on the icon's SVG element.
=> Update polaris-icon to v2.0.0

CHANGELOG.md, addon/components/polaris-button-group/item.js, docs/button-group.md, tests/dummy/app/templates/index.hbs, tests/integration/components/polaris-button-group-test.js
Fixes #120:
Found that the reason I couldn't get this working yesterday was that when the code doesn't explicitly add the item wrapper component around each button in the group, we can't handle the focus/blur events on the [auto-added wrapper `div`s](https://github.com/smile-io/ember-polaris/blob/b91554f944ac2c3a44815de50571c7e30bf0f213/addon/components/polaris-button-group.js#L48). Once the user explicitly adds the item wrapper component around each button, this works fine; I've added a note to the documentation about this.
I guess we could also hack something together on the auto-wrapper system to handle focus/blur on the wrapper `div`s, but that'd be pretty dirty and probs not worth doing...
=> Fix focused button group item z-index

CHANGELOG.md, addon/components/polaris-popover.js, addon/components/polaris-thumbnail.js
Fixes [this deprecation warning](https://travis-ci.org/smile-io/ember-polaris/jobs/378581532#L996) on Travis, caused by calling `Ember.warn` without passing an ID for the warning.
=> Add IDs to `Ember.warn` calls

CHANGELOG.md, tests/integration/components/polaris-page-test.js
Fixes [this breadcrumb test failure](https://travis-ci.org/smile-io/ember-polaris/jobs/378581532#L926) that seems to be due to URL configuration on Travis...
=> Fix failing breadcrumb test on Travis

CHANGELOG.md, addon/templates/components/polaris-action-list/section.hbs, tests/integration/components/polaris-action-list-test.js
Just noticed that we had a missing class on one of the elements in `polaris-action-list` which was breaking some styling.
=> Add missing class name on `polaris-action-list` section

CHANGELOG.md, addon/templates/components/polaris-layout/annotation.hbs, tests/integration/components/polaris-layout-test.js
Adds the [new-to-v2.0.0 subdued text style](https://github.com/Shopify/polaris/compare/v1.12.4...v2?diff=split#diff-7fd5adef3605c29a5ce32bc357cdf5ef) to `polaris-layout/annotated-section`'s description text.
=> Update layout annotated section to v2.0.0

CHANGELOG.md, addon/templates/components/polaris-checkbox.hbs, addon/templates/components/polaris-radio-button.hbs, tests/integration/components/polaris-checkbox-test.js, tests/integration/components/polaris-choice-list-test.js, tests/integration/components/polaris-radio-button-test.js
Switches the `div`s inside [`polaris-radio-button`](https://github.com/Shopify/polaris/compare/v1.12.4...v2?diff=split#diff-c8fd35a0b10ec3c24926318011c0ae40) and [`polaris-checkbox`](https://github.com/Shopify/polaris/compare/v1.12.4...v2?diff=split#diff-07693469831f3bf8790b8c358d194d7c) for `span`s, as per the v2.0.0 React components.
=> Update polaris-radio-button and polaris-checkbox to v2.0.0

CHANGELOG.md, addon/components/polaris-tag.js, addon/templates/components/polaris-tag.hbs, docs/tag.md, tests/integration/components/polaris-tag-test.js
Adds the [new `disabled` property](https://github.com/Shopify/polaris/blob/fcb570f9e3664642fded60f4943b375032cf8271/src/components/Tag/Tag.tsx#L15) to `polaris-tag`.
=> Update polaris-tag to v2.0.0

addon/components/polaris-popover.js, addon/templates/components/polaris-popover.hbs, docs/popover.md, tests/integration/components/polaris-popover-test.js
Adds the [`onClose`](https://polaris.shopify.com/components/overlays/popover/onClose) property to the popover component
=> Add onClose attribute to polaris-popover

CHANGELOG.md, addon/templates/components/polaris-layout/annotation.hbs
@vladucu pointed out that we were still using `<div class="Polaris-TextContainer">` in `polaris-layout/annotation`, since that component pre-dates our implementation of `polaris-text-container`. Updating it to use the component instead of a simple `div` 👍
=> Use `polaris-text-container` in `polaris-layout/annotation`

CHANGELOG.md, addon/components/polaris-icon.js, addon/components/polaris-spinner.js, addon/mixins/components/svg-handling.js, addon/templates/components/polaris-icon.hbs, addon/templates/components/polaris-spinner.hbs
Fixes #116 by abstracting out the SVG `fill` attribute processing from `polaris-icon` into a mixin and applying it to the SVG rendered by `polaris-spinner` as well.
=> Make `polaris-spinner` respect the `color` property

CHANGELOG.md, addon/components/render-content.js, addon/templates/components/render-content.hbs, app/components/render-content.js, tests/integration/components/render-content-test.js
Quick little enhancement that allows us to render both "simple" values (e.g. `componentContent="some text"`) and component definitions (passed as e.g. `componentContent=(component "my-cool-component" color="pink")`) using the same one-liner, `{{render-content componentContent}}`.
This opens the door for us to be able to easily support passing child content to `ember-polaris` components without having to go down the route we've taken before of adding e.g. separate `label` and `labelComponent` properties to Polaris components.
=> Support React-style content rendering

CHANGELOG.md, addon/components/polaris-checkbox.js, addon/components/polaris-choice.js, addon/components/polaris-choice/label.js, addon/components/polaris-description-list.js, addon/components/polaris-radio-button.js, addon/templates/components/polaris-choice/label.hbs, addon/templates/components/polaris-description-list.hbs, docs/checkbox.md, docs/description-list.md, docs/radio-button.md, tests/integration/components/polaris-checkbox-test.js, tests/integration/components/polaris-description-list-test.js
Our implementations of `polaris-checkbox` and `polaris-description-list` had previously had separate `label`/`labelComponent` properties etc. which was out of alignment with the React implementations and a nuisance for developers to remember. With this PR, the following become deprecated:
- `labelComponent` for `polaris-checkbox`;
- `termComponent` and `descriptionComponent` for `polaris-description-list#items`.
Instead, the components can now be simply passed as `label`, `term` and `description` respectively.
=> Use `render-component` to align component interfaces with React implementations

CHANGELOG.md, README.md, addon/components/polaris-data-table.js, addon/components/polaris-data-table/cell.js, addon/components/polaris-data-table/heading.js, addon/components/polaris-data-table/navigation.js, addon/components/polaris-data-table/row.js, addon/components/polaris-data-table/total.js, addon/helpers/get-array-item.js, addon/helpers/polaris-data-table/insert-presentational-cell.js, addon/mixins/components/svg-handling.js, addon/templates/components/polaris-data-table.hbs, addon/templates/components/polaris-data-table/cell.hbs, addon/templates/components/polaris-data-table/heading.hbs, addon/templates/components/polaris-data-table/navigation.hbs, addon/templates/components/polaris-data-table/row.hbs, addon/templates/components/polaris-data-table/total.hbs, app/components/polaris-data-table.js, app/components/polaris-data-table/cell.js, app/components/polaris-data-table/heading.js, app/components/polaris-data-table/navigation.js, app/components/polaris-data-table/row.js, app/components/polaris-data-table/total.js, app/helpers/get-array-item.js, app/helpers/polaris-data-table/insert-presentational-cell.js, docs/data-table.md, tests/integration/components/polaris-data-table-test.js
Depends on #142 in order to be able to render arbitrary components in table cells.
Adds full implementation of the Polaris [data table](https://polaris.shopify.com/components/lists-and-tables/data-table) component:
Reproducing the demos on the Shopify component documentation page:
Data table with footer:
Data table with sortable columns (when the sorting updates without clicking it's because I pressed `Enter` while the column heading was focussed):
=> Add data table component

CHANGELOG.md, addon/templates/components/polaris-label.hbs
Adds the `Polaris-Label--hidden` class that was missing from `polaris-label` when `hidden` was truthy.
=> Add missing hidden class to `polaris-label`

CHANGELOG.md, addon/components/wrapper-element.js, tests/integration/components/wrapper-element-test.js
Allows us to pass arbitrary attributes to the internal `wrapper-element` component and have them be bound to the rendered element (if there is one).
=> Auto-bind wrapper-element attributes

CHANGELOG.md, README.md, addon/components/polaris-label.js, addon/components/polaris-labelled.js, addon/components/polaris-range-slider.js, addon/templates/components/polaris-range-slider.hbs, addon/utils/id.js, app/components/polaris-range-slider.js, app/utils/id.js, docs/radio-button.md, docs/range-slider.md, tests/integration/components/polaris-range-slider-test.js
Adds a full implementation of the Polaris [range slider](https://polaris.shopify.com/components/forms/range-slider) component:
=> Add range slider component

CHANGELOG.md, addon/components/polaris-text-field.js
The `polaris-text-field` uses ember-lifeline to add an event listener for the `keyup` event on the input field. It [doesn't require](https://github.com/ember-lifeline/ember-lifeline/blob/master/addon/mixins/dom.js#L57) a selector to be passed in, and worked fine in the dummy app. However when pulled into other apps it seems to be having issues (throws error: `Called addEventListener with selector not found in DOM: keyup`) so to be safe I'm passing the selector, which fixes the error and still works as expected.
=> Pass selector to value listener in polaris-text-field

CHANGELOG.md, docs/button-group.md, docs/form-layout.md, docs/stack.md
At present, 4 of the components in `ember-polaris` auto-wrap their child elements in `div`s - `polaris-button-group`, `polaris-form-layout`, `polaris-form-layout/group` and `polaris-stack`. If any of these components are used with dynamic contents (e.g. with an `if`- or `each`-block inside), whenever an item is added or removed a Glimmer error can occur. Unfortunately I don't think we can detect this possibility and avoid it automatically (certainly not quickly), so I thought it was worth adding notes and examples to the docs for those components affected.
=> Add notes about avoiding Glimmer error under dynamic usages of auto-wrapping components

CHANGELOG.md, addon/components/polaris-callout-card.js, addon/templates/components/polaris-callout-card.hbs
`polaris-callout-card` was previously a tagless component, which meant that it was impossible to apply classes to directly. This small PR refactors the component to have the `div.Polaris-Card` as its element.
=> Allow classes for `polaris-callout-card`

.eslintignore, .eslintrc.js, .gitignore, .npmignore, .template-lintrc.js, .travis.yml, README.md, config/ember-try.js, index.js, package.json, testem.js, tests/dummy/config/optional-features.json, yarn.lock
Will merge this in a main `dev` branch and basing Polaris resource list on top of these
`ember-cli` upgrade diff [here](https://github.com/ember-cli/ember-new-output/compare/v3.1.4...v3.4.2)
=> Upgrade Ember to 3.4

CHANGELOG.md, README.md, addon/components/polaris-inline-error.js, addon/templates/components/polaris-inline-error.hbs, app/components/polaris-inline-error.js, docs/inline-error.md, package.json, tests/integration/components/polaris-inline-error-test.js, yarn.lock
=> Implement Polaris inline-error component

addon/components/polaris-drop-zone/file-upload.js, package.json, yarn.lock
We modified the style guide to have the ability to group single line & multi line fns (computed props) by their accessors(public vs private) along with other public & private props. This PR autofixes to follow it across files.
=> Bump style guide & autofix files

CHANGELOG.md, addon/components/polaris-checkbox.js, addon/components/polaris-choice.js, addon/components/polaris-choice/label.js, addon/templates/components/polaris-checkbox.hbs, addon/templates/components/polaris-choice.hbs, tests/integration/components/polaris-choice-test.js
Finishes https://github.com/smile-io/ember-polaris/issues/186
Diff [here](https://github.com/Shopify/polaris/compare/v2.2.0...v2.11.0?diff=split#diff-29260b22317e444058d1188413079747)
This is mostly just an update to `polaris-choice`, the only update to `polaris-checkbox` was sending down the `disabled` attribute.
=> Upgrade v2.11.0 checkbox/choice

CHANGELOG.md, addon/templates/components/polaris-setting-toggle.hbs, docs/setting-toggle.md, tests/integration/components/polaris-setting-toggle-test.js
Just found that the `disabled` and `loading` options in `polaris-setting-toggle`'s `action` hash weren't supported, so added them in.
=> Add support for disabled and loading states to polaris-setting-toggle

addon/components/polaris-skeleton-page.js, addon/templates/components/polaris-skeleton-page.hbs, addon/templates/components/polaris-skeleton-page/action.hbs, tests/integration/components/polaris-skeleton-page-test.js
fixes #202
Diff [here](https://github.com/Shopify/polaris/compare/v2.2.0...v2.11.0#diff-4b7984ed7d7a9bca1981d7be745fcdc3R15)
Related, opened a [PR](https://github.com/smile-io/ember-smile-polaris/pull/116) on `ember-smile-polaris` that updates to use the `dev` branch on `ember-polaris` and remove the custom skeleton-page component we had there to support singleColumn
=> Update skeleton-page component

CHANGELOG.md, addon/components/polaris-checkbox.js, addon/components/polaris-choice-list.js, addon/components/polaris-choice/label.js, addon/templates/components/polaris-checkbox.hbs, addon/templates/components/polaris-choice-list.hbs, addon/templates/components/polaris-choice.hbs, addon/templates/components/polaris-radio-button.hbs, tests/integration/components/polaris-choice-list-test.js
Finishes https://github.com/smile-io/ember-polaris/issues/188
Diff [here](https://github.com/Shopify/polaris/compare/v2.2.0...v2.11.0?diff=split#diff-f9b830900da70d07e7b83b882b9e48d7)
=> Upgrade v2.11.0 choicelist

addon/templates/components/polaris-card/section.hbs
Noticed a couple of tests on a few recent Polaris v2.11.0 update branches were failing on `ember-beta` and `ember-canary`, this branch puts a fix in for the error:
=> Fix test error from using string as component name

CHANGELOG.md, addon/components/polaris-inline-error.js, addon/components/polaris-labelled.js, addon/templates/components/polaris-labelled.hbs, tests/integration/components/polaris-labelled-test.js
Closes #215
I didn't update to use `ember-test-selectors` here simply because the existing tests are just straight ports of the React implementation's tests. Let me know if you guys feel like we should make that update anyway and I'll do it :+1:
=> Update labelled to v2.11.0

CHANGELOG.md, addon/components/polaris-date-picker.js, addon/components/polaris-date-picker/month.js, addon/components/polaris-date-picker/weekday.js, addon/helpers/polaris-date-picker/derive-range.js, addon/templates/components/polaris-date-picker.hbs, addon/templates/components/polaris-date-picker/day.hbs, addon/templates/components/polaris-date-picker/month.hbs, addon/utils/dates.js, app/helpers/polaris-date-picker/derive-range.js, tests/integration/components/polaris-date-picker-test.js
Diff [here](https://github.com/Shopify/polaris/compare/v2.2.0...v2.11.0?diff=split#diff-31dd30c75130536eea45b3bccfbb92b9)
Finishes https://github.com/smile-io/ember-polaris/issues/198
=> Upgrade v2.11.0 date picker

CHANGELOG.md, addon/components/polaris-button-group.js, addon/components/polaris-button-group/item.js, docs/button-group.md, tests/integration/components/polaris-button-group-test.js
Diff [here](https://github.com/Shopify/polaris/compare/v2.2.0...v2.11.0#diff-ae076cc3c15cddac2f460c6941d4626f)
Finishes https://github.com/smile-io/ember-polaris/issues/229
=> Upgrade button-group to v2.11.0

addon/components/polaris-inline-error.js, addon/templates/components/polaris-inline-error.hbs
Noticed that we were hitting some warnings in tests due to having `data-test-*` properties defined on `polaris-inline-error`, which is a tagless component:
By naming these camel-cased instead of dasherized, `ember-test-selectors` doesn't attempt to bind them to the component's tag.
=> Fix "empty tagName" warnings coming from polaris-inline-error

CHANGELOG.md, addon/components/polaris-breadcrumbs.js, addon/templates/components/polaris-breadcrumbs.hbs, tests/integration/components/polaris-breadcrumbs-test.js
Fixes #240 by swallowing the click event object when invoking breadcrumb actions.
=> Remove click event object from breadcrumb action args

CHANGELOG.md, addon/components/polaris-action-list/section.js, tests/integration/components/polaris-action-list-test.js
Fix for https://github.com/smile-io/ember-polaris/issues/162
=> Fix action item actions event bubbling

CHANGELOG.md, addon/components/polaris-data-table.js
Moved this fix out of https://github.com/smile-io/ember-polaris/pull/243 to be in it's own PR since we're going to hold off on merging https://github.com/smile-io/ember-polaris/pull/243 until we upgrade to a version of Polaris where they include the fix as well.
Copied description from 243:
As for the heights not calculating correctly, we were using `childNodes` which was also grabbing text nodes, whereas we want just html elements. The [React version](https://github.com/Shopify/polaris-react/blob/master/src/components/DataTable/DataTable.tsx#L281) gets away with using `childNodes` because they use `row.childNodes as NodeListOf<HTMLElement>` so I'm guessing this is a TS thing where it will only grab elements and filter out the text nodes.
=> Use children vs. childNodes in data-table cell height calc

CHANGELOG.md, addon/components/polaris-data-table.js
Cell heights weren't being recalculated when underlying data changed (https://github.com/smile-io/ember-polaris/issues/161)
The recalculation issue is [fixed in Polaris](https://github.com/Shopify/polaris-react/blob/master/src/components/DataTable/DataTable.tsx#L108-L113) by recalculating height when the `DataTable` component updates.
~~This fix doesn't appear in the React version until **v3.0.0-beta.11**, so we should hold off on merging until we have a 3.0 version of ember-polaris just to keep our versions in sync.~~ (we'll ship now and add a comment)
=> Fix data table height not calculating correctly

CHANGELOG.md, addon/components/polaris-page.js, addon/components/polaris-page/action.js, addon/components/polaris-page/header.js, addon/templates/components/polaris-page.hbs, addon/templates/components/polaris-page/action.hbs, addon/templates/components/polaris-page/header.hbs, docs/page.md, tests/dummy/app/templates/index.hbs, tests/integration/components/polaris-page-test.js
Pulls the functionality added in [v1.7.9](https://github.com/smile-io/ember-polaris/releases/tag/v1.7.9) into v2.
Screen grab (minus SVG icons 😬) showing the new functionality:
=> Add action groups to page component

addon/components/polaris-resource-list/filter-control.js, yarn.lock
On my local running `yarn lint:js` did show the same build failure as CI. This PR fixes the borked file.
=> Fix prettier for the broken branch

addon/components/polaris-resource-list/filter-control.js, tests/integration/components/polaris-resource-list/filter-control/filter-value-selector-test.js, tests/integration/components/polaris-text-field-test.js
Turns out the default value notation I'd used in the resource list filter control when handling `appliedFilters` doesn't work as I'd expected it to, leading to null ref errors when adding/removing filters 🤦‍♂️ This PR fixes that by using some less fancy notation which actually gets the job done 🙏
=> Handle null appliedFilters in resource list filter control

CHANGELOG.md, addon/components/polaris-popover.js, addon/components/polaris-popover/content.js, addon/templates/components/polaris-popover.hbs, addon/templates/components/polaris-popover/content.hbs
`polaris-popover` really needs to be rebuilt from scratch as a direct port of the React implementation, but until then this is a quick implementation of the `fullWidth` property.
=> Add `fullWidth` support to `polaris-popover`

CHANGELOG.md, addon/templates/components/polaris-callout-card.hbs
Adds support for props such as `primary` etc. on `polaris-callout-card` actions
=> Pass action properties through to callout card buttons

CHANGELOG.md, addon/templates/components/polaris-page/header.hbs
`polaris-page`'s `primaryAction` should support the `destructive` flag as the React implementation does, but until this point it didn't 🤷‍♂️
=> Add "destructive" support to page primary action

CHANGELOG.md, addon/components/polaris-choice-list.js, tests/integration/components/polaris-choice-list-test.js
We found that swapping the array passed to `polaris-choice-list` as the `selected` property didn't trigger an update of which options were marked as selected. This should fix the issue... 🙏
=> Ensure choice list updates properly when "selected" array is swapped out

CHANGELOG.md, addon/components/polaris-choice.js, addon/templates/components/polaris-choice.hbs, tests/integration/components/polaris-choice-test.js
This is supported by the React implementation, so we should probably support it too 😉
=> Allow passing a component as polaris-choice-list's helpText property

CHANGELOG.md, addon/components/polaris-progress-bar.js, tests/integration/components/polaris-progress-bar-test.js
Because the React Polaris components use TypeScript, their `ProgressBar` component handles non-numeric values quite cleanly. Our implementation unfortunately did not, so in this PR I've updated its behaviour to match the Shopify version's:
- non-numeric `progress` values result in the bar being rendered without a `value` attribute, making it appear empty;
- Values of +/-infinity are now clamped to 100 and 0 internally respectively.
=> Handle non-numeric progress values in progress bar

CHANGELOG.md, addon/components/polaris-layout/annotated-section.js, addon/components/polaris-layout/annotation.js, addon/templates/components/polaris-layout/annotation.hbs, docs/layout.md, tests/integration/components/polaris-layout-test.js
Until now, `polaris-layout/annotated-section`'s `annotation` supported being used in block form, with the block content being used in place of the `description` property. However, this block usage isn't accessible via `polaris-layout/annotated-section`'s public API; as a result I'm removing this behaviour in favour of accepting a component definition or `componentName`/`props` hash as the `description` to allow rendering arbitrary content directly via the public API.
=> Allow passing component for annotated layout section's description

CHANGELOG.md, addon/templates/components/polaris-text-field/resizer.hbs
Noticed that multiline text fields were rendering a couple of lines taller than expected. This was something we'd fixed internally at @smile-io but forgotten about, and recently got exposed in our apps during some development work 🤷‍♂️
=> Fix height bug on multiline text field

CHANGELOG.md, addon/services/sticky-manager.js
Noticed today while testing `polaris-sticky` in one of our apps that the `manageStickyItems` method in `sticky-manager` has an infinite loop, figured I should _probably_ fix it 🤦‍♂️
=> Break infinite loop in sticky manager

addon/components/polaris-banner.js, addon/templates/components/polaris-banner.hbs, tests/integration/components/polaris-banner-test.js
Tweaks `polaris-banner` to add the new `div` around the primary action, and sets the primary action button size to `slim` when `withinContentContainer` is truthy. Also added a `TODO` to update the icons when we figure out how to progress with the `@shopify/polaris-icons` package 🙏
=> Update banner to Polaris v3.10.0

addon/components/polaris-avatar.js, addon/templates/components/polaris-avatar.hbs, tests/integration/components/polaris-avatar-test.js
Updates `polaris-avatar` to match Polaris v3.10.0. I haven't added the new `isServer` functionality since we don't need it at this point. Also dropped the old tests in favour of porting the new ones added in `polaris-react` since we initially built `polaris-avatar`.
=> Update avatar to Polaris v3.10.0

addon/components/polaris-action-list.js, addon/components/polaris-action-list/item.js, addon/components/polaris-action-list/section.js, addon/templates/components/polaris-action-list.hbs, addon/templates/components/polaris-action-list/item.hbs, addon/templates/components/polaris-action-list/section.hbs, tests/integration/components/polaris-action-list-test.js
Updates `polaris-action-list` and child components to match Polaris v3.10.0. I haven't added the new scroll functionality since we don't currently need it anywhere and don't have an implementation of the Polaris `Scrollable` component that we'd need for it anyway.
=> Update action list to v3.10.0

addon/components/polaris-unstyled-link.js, tests/integration/components/polaris-unstyled-link-test.js
Updates the comments/JSDoc for `polaris-unstyled-link`, adds the `download` property, and adds ports of the applicable React tests.
=> Update unstyled link to Polaris v3.10.0

addon/components/polaris-card/section-header.js, addon/templates/components/polaris-card.hbs, addon/templates/components/polaris-card/section-header.hbs
Tweaks logic behind when card header renders and prevents potential glimmer errors when card has dynamic footer actions.
EDIT: also adds support for rendering components as card section titles (missed this file in the diff when I made the initial changes 🤦‍♂️)
=> Update card to Polaris v3.10.0

addon/components/polaris-date-picker/day.js
Tweaks the logic on `polaris-date-picker`'s `inHoveringRange` to match the React implementation.
=> Update date picker to Polaris v3.10.0

addon/components/polaris-form.js, tests/integration/components/polaris-form-test.js
Defaults `polaris-form`'s `method` property to POST.
=> Update form to Polaris v3.10.0

addon/components/polaris-form-layout/group.js, tests/integration/components/polaris-form-layout-test.js
Adds a "grouped" class to `polaris-form-layout/group` instances with `condensed=false`.
=> Update form layout to Polaris v3.10.0

addon/components/polaris-link.js, addon/templates/components/polaris-link.hbs, tests/integration/components/polaris-link-test.js
Adds support for `monochrome` `polaris-link`s and ensures the correct `type` is used when link buttons are rendered.
=> Update link to Polaris v3.10.0

tests/integration/components/polaris-empty-search-result-test.js
Tweaks the description on one of the `polaris-empty-search-result` tests, no other changes needed to match the React implementation 🤷‍♂️
=> Update empty search result to Polaris v3.10.0

addon/components/polaris-option-list.js, addon/templates/components/polaris-option-list.hbs, addon/templates/components/polaris-option-list/option.hbs, tests/integration/components/polaris-option-list-test.js, tests/integration/components/polaris-option-list/checkbox-test.js, tests/integration/components/polaris-option-list/option-test.js
Updates usage of the `role` property on `polaris-option-list` and tweaks a few test descriptions.
=> Update option list to Polaris v3.10.0

addon/-private/drop-zone-state.js, addon/components/polaris-drop-zone.js, addon/components/polaris-drop-zone/file-upload.js, addon/templates/components/polaris-drop-zone/file-upload.hbs, addon/utils/drop-zone.js, tests/integration/components/polaris-drop-zone-test.js
Adds the React implementation's [reset inputHTMLElement to allow duplicate files](https://github.com/Shopify/polaris-react/commit/a81f09471f91be9a8f42d87dd6a572db9984b0f4) change.
=> Update drop zone to Polaris v3.10.0

addon/components/polaris-text-style.js, addon/templates/components/polaris-text-style.hbs, tests/integration/components/polaris-text-style-test.js
Updates the elements used so that `span` is now used when `variation` is `'strong'`, and DRYs up the template slightly by using `wrapper-element`.
=> Update text style to Polaris v3.10.0

addon/components/polaris-resource-list.js, addon/components/polaris-resource-list/filter-control/date-selector.js, addon/components/polaris-resource-list/item.js, addon/components/polaris-resource-list/loading-overlay.js, addon/components/polaris-unstyled-link.js, addon/templates/components/polaris-resource-list.hbs, addon/templates/components/polaris-resource-list/item.hbs, addon/templates/components/polaris-resource-list/loading-overlay.hbs, app/components/polaris-resource-list/loading-overlay.js, tests/helpers/component-attribute-capture.js, tests/integration/components/polaris-resource-list-test.js, tests/integration/components/polaris-resource-list/bulk-actions-test.js, tests/integration/components/polaris-resource-list/filter-control-test.js, tests/integration/components/polaris-resource-list/filter-control/date-selector-test.js, tests/integration/components/polaris-resource-list/filter-control/filter-creator-test.js, tests/integration/components/polaris-resource-list/filter-control/filter-value-selector-test.js, tests/integration/components/polaris-resource-list/item-test.js
Adds support for `alternateTool` to `polaris-resource-list`, improves handling of loading state, improves item link handling on click events, and updates the resource list subcomponents with the tweaks from Polaris v3.10.0.
=> Update resource list to Polaris v3.10.0

addon/components/polaris-spinner.js
Spinner icons are under `/images/` not `/illustrations/` 😝
=> Fix spinner icon paths

addon/components/polaris-text-field.js, addon/components/polaris-text-field/spinner.js, addon/templates/components/polaris-text-field.hbs, addon/templates/components/polaris-text-field/spinner.hbs, tests/integration/components/polaris-text-field-test.js
Adds a new `showCharacterCount` attribute as well as methods for holding down the buttons in the number spinners to slowly increment/decrement the current number value.
=> Update textfield to Polaris v3.10.0 

addon/components/polaris-button.js, addon/templates/components/polaris-button.hbs, tests/integration/components/polaris-button-test.js
https://github.com/smile-io/ember-polaris/pull/291 inadvertently changed the interface for `polaris-button`, such that the mouse event object was passed to the `onClick`, `onFocus` and `onBlur` actions on invocation, which it never was before my refactor. This change removes the erroneous event object, fixing the signature for `onClick`, `onFocus` and `onBlur` :+1:
=> Remove event object from button mouse action handler invocations

CHANGELOG.md, addon/components/polaris-skeleton-thumbnail.js, app/components/polaris-skeleton-thumbnail.js, tests/integration/components/polaris-skeleton-thumbnail-test.js
Adds the Polaris [`SkeletonThumbnail` component](https://github.com/Shopify/polaris-react/blob/bba36af2ad10ba9626bba168b52e2e9222ac4c60/src/components/SkeletonThumbnail/SkeletonThumbnail.tsx) as it stands in v3.10.0.
=> Add skeleton thumbnail component

addon/components/polaris-text-field.js
Saw a couple of `Cannot set read-only property "focus" on object` errors logged for one of our apps. `focus` is part of the component's `State` in the React implementation so seems like it should be writeable...
=> Make text field "focus" property writeable

addon/components/polaris-choice-list.js, addon/templates/components/polaris-choice-list.hbs, docs/choice-list.md, tests/integration/components/polaris-choice-list-test.js
This adds support for an `extra` component to be used for `polaris-choice-list` choices aka `renderChildren` in react world
=> Add support for choice-list extra component aka renderChildren

addon/components/polaris-choice-list.js, addon/templates/components/polaris-choice-list.hbs, docs/choice-list.md, tests/integration/components/polaris-choice-list-test.js
This is a follow up on #318 
Found out that with #318, we'll always render the wrapping `Polaris-ChoiceList__ChoiceChildren` div when there's a `childComponent` for a choice, which cause some extra spacing.
This:
- changes so that by default we render the `childComponent` only when the choice is selected
- adds an extra `alwaysRenderChildComponent` property, which when `true` will always render the `childComponent`
=> Fix rendering choice-list child components

.eslintrc.js, .template-lintrc.js, package.json, yarn.lock
Whenever we need to update eslint config for ember apps/addons, we need to update it in [eslint-plugin-smile-ember](https://github.com/smile-io/eslint-plugin-smile-ember) & release it.
Other linting configs can be updated in our [ember-styleguide](https://github.com/smile-io/ember-styleguide) project & once released, we can run `yarn setup-smile-styleguide` to update relevant configs & packages.
=> Update smile linting & code formatting tools

addon/components/render-content.js, addon/helpers/is-component-definition.js
Found that our method of detecting component definitions was broken in production builds where constructor names seem to be getting minified. This method follows Glimmer's [way](https://github.com/glimmerjs/glimmer-vm/blob/master/packages/@glimmer/runtime/lib/component/curried-component.ts#L11) of detecting component definitions (thx @vladucu!) to avoid such issues 🙏 
Also DRYs up the component definition detection in `render-content` so we won't face any additional surprises if this breaks again in the future 😅
=> Fix component definition detection

addon/-private/drop-zone-state.js, addon/components/polaris-drop-zone.js, addon/components/polaris-drop-zone/file-upload.js, addon/templates/components/polaris-drop-zone.hbs, addon/templates/components/polaris-drop-zone/file-upload.hbs, addon/utils/drop-zone.js, package.json, tests/dummy/app/controllers/dropzone.js, tests/dummy/app/templates/dropzone.hbs, tests/integration/components/polaris-drop-zone-test.js, yarn.lock
Tests are failing on beta & canary, likely related to ember-decorators/ember-decorators#451
=> Refactor polaris-drop-zone

.travis.yml, package.json, yarn.lock
Disables ember-beta temporarily and remove `ember-array-helper` which is no longer required since ember `3.10`
=> Disable ember-beta tests & remove useless dependency

addon/components/polaris-range-slider.js, addon/templates/components/polaris-range-slider.hbs
[DEV-77](https://smileio.atlassian.net/secure/RapidBoard.jspa?rapidView=6&modal=detail&selectedIssue=DEV-77)
Updates `PolarisRangeSlider` to tagless component, ES6 classes, and angle bracket syntax.
Dummy app:
^ I'm not sure what's going on with the positioning here but this is also happening on `master` but not in any apps that actually use `ember-polaris`, so I'm guessing it's just something weird with the way styles are being pulled from Polaris into the dummy app.
=> Modernize polaris-range-slider component

addon/components/polaris-radio-button.js, addon/templates/components/polaris-radio-button.hbs, tests/integration/components/polaris-radio-button-test.js
[DEV-76](https://smileio.atlassian.net/browse/DEV-76)
Updates `PolarisRadioButton` to tagless component, ES6 classes, and angle bracket syntax.
Dummy app:
=> Modernize polaris-radio-button component

addon/components/polaris-pagination.js, addon/templates/components/polaris-pagination.hbs
[DEV-73](https://smileio.atlassian.net/secure/RapidBoard.jspa?rapidView=6&modal=detail&selectedIssue=DEV-73)
Updates `PolarisPagination` and all sub-components to tagless component, ES6 classes, and angle bracket syntax.
Not really demoable from the dummy app, it was two buttons next to each other, and the icons don't render anyway so it's not much to look at 😛
=> Modernize polaris-pagination component

addon/components/polaris-link.js, addon/templates/components/polaris-link.hbs, package.json, yarn.lock
[DEV-69](https://smileio.atlassian.net/secure/RapidBoard.jspa?rapidView=6&modal=detail&selectedIssue=DEV-69)
Updates `PolarisLink` to tagless component, ES6 classes, and angle bracket syntax.
Notable change:
- Added `ember-event-helpers` to use with the `on` modifier so we can stop propagation via template helper.
=> Modernize polaris-link component

addon/components/polaris-resource-list.js, addon/components/polaris-resource-list/bulk-actions.js, addon/components/polaris-resource-list/bulk-actions/bulk-action-button.js, addon/components/polaris-resource-list/checkable-button.js, addon/components/polaris-resource-list/filter-control.js, addon/components/polaris-resource-list/filter-control/date-selector.js, addon/components/polaris-resource-list/filter-control/filter-creator.js, addon/components/polaris-resource-list/filter-control/filter-value-selector.js, addon/components/polaris-resource-list/item.js, addon/components/polaris-resource-list/loading-overlay.js, addon/templates/components/polaris-resource-list.hbs, addon/templates/components/polaris-resource-list/bulk-actions.hbs, addon/templates/components/polaris-resource-list/bulk-actions/bulk-action-button.hbs, addon/templates/components/polaris-resource-list/checkable-button.hbs, addon/templates/components/polaris-resource-list/filter-control.hbs, addon/templates/components/polaris-resource-list/filter-control/date-selector.hbs, addon/templates/components/polaris-resource-list/filter-control/filter-creator.hbs, addon/templates/components/polaris-resource-list/filter-control/filter-value-selector.hbs, addon/templates/components/polaris-resource-list/item.hbs, addon/templates/components/polaris-resource-list/loading-overlay.hbs
[DEV-78](https://smileio.atlassian.net/secure/RapidBoard.jspa?rapidView=6&modal=detail&selectedIssue=DEV-78)
Updates `PolarisResourceList` and all sub-components to tagless component, ES6 classes, and angle bracket syntax.
Notable changes:
- Removed `wrapperId` from the main `polaris-resource-list` component. It was only used as a selector in order to set the `listNode` attribute (`ul.Polaris-ResourceList`). This was breaking in tests because the `ul` wasn't rendered yet when setting the node in the component file, so instead I added a `{{did-insert this.insertListNode}}` on the `ul` itself and set the reference directly in there.
- Used the `(element)` template helper in favor of our `WrapperElement` component wherever I could.
Dummy app:
=> Modernize polaris-resource-list components

addon/components/polaris-popover.js, addon/components/polaris-popover/content.js, addon/templates/components/polaris-popover.hbs, addon/templates/components/polaris-popover/content.hbs
[DEV-74](https://smileio.atlassian.net/secure/RapidBoard.jspa?rapidView=6&modal=detail&selectedIssue=DEV-74)
Updates `PolarisPopover` and subcomponent to tagless components, ES6 classes, and angle bracket syntax.
Dummy app:
=> Modernize polaris-popover components

addon/components/polaris-display-text.js, addon/templates/components/polaris-display-text.hbs, addon/templates/components/polaris-drop-zone.hbs, addon/templates/components/polaris-empty-state/details.hbs, addon/templates/components/polaris-page/header.hbs, addon/templates/components/polaris-skeleton-page.hbs, docs/display-text.md, tests/integration/components/polaris-display-text-test.js
We rename here `tagName` -> `htmlTag` (as a match for `polaris-react`'s `element` property), because using `tagName` with angle-bracket syntax seems to result in adding an extra wrapper with `tagName` around the component.
=> Modernize display-text component

addon/components/polaris-button.js, addon/components/polaris-link.js, addon/components/polaris-page/action.js, addon/components/polaris-resource-list/checkable-button.js, addon/components/polaris-unstyled-link.js, addon/templates/components/polaris-button.hbs, addon/templates/components/polaris-link.hbs, addon/templates/components/polaris-page/action.hbs, addon/templates/components/polaris-resource-list/checkable-button.hbs, tests/integration/components/polaris-button-test.js, tests/integration/components/polaris-link-test.js, tests/integration/components/polaris-page-test.js, tests/integration/components/polaris-resource-list/checkable-button-test.js, tests/integration/components/polaris-unstyled-link-test.js
When we replaced usage of `mapEventToAction` utility for click handlers, we
introduced back currying of the click event to the action handlers. This fixes
it.
=> Stop curring click event to action handlers

addon/templates/components/polaris-button.hbs, tests/integration/components/polaris-button-test.js
This fixes the issue we've been seeing in our testing with the DropZone
click handling not working correctly.
=> Fix PolarisButton click propagation

CHANGELOG.md, addon/templates/components/polaris-card.hbs
Found this morning that when using a `PolarisCard` with `@sectioned={{true}}` in block mode, the yielded hash looks like `{section: undefined}` 😬 This change makes sure `section` is populated correctly, and also adds a `Section` property as a parallel to the yielded hash when `PolarisCard` is used without `@sectioned={{true}}`.
=> Fix yielded section in sectioned card

addon/components/polaris-data-table.js, addon/templates/components/polaris-data-table.hbs
Cell heights aren't getting recalculated once the `cellText` (which comes from `@rows` data) gets rendered inside the cell, so its resulting in broken cells where they're are all the initial default height regardless of how much content is rendered inside of them.
=> Pass rows attribute to did-update modifier in PolarisDataTable

addon/components/key-event-listener.js, addon/components/polaris-pagination.js, addon/templates/components/polaris-choice-list.hbs, addon/templates/components/polaris-pagination.hbs, package.json, yarn.lock
This fixes failing tests on `ember-beta`/`ember-canary`. This is a major
upgrade for `ember-keyboard` because it drops support for Ember pre `3.8`, but we are compatible with
`3.12+`, so not a major for us.
There are still some deprecations, we'll fix these later on.
=> Upgrade ember-keyboard to v6

addon/components/polaris-action-list.hbs, addon/components/polaris-action-list.js, addon/components/polaris-action-list/item.js, addon/components/polaris-action-list/section.hbs, addon/components/polaris-action-list/section.js, addon/components/polaris-icon.js, addon/services/polaris-app-provider.js, addon/utils/color-new-design-language.js, app/services/polaris-app-provider.js, app/utils/color-new-design-language.js, tests/integration/components/polaris-action-list-test.js, tests/integration/components/polaris-icon-test.js
Adds `polaris-app-provider` service that we use to have support for the
`newDesignLanguage`. Kind of equivalent to `polaris-react`'s `AppProvider`
component, but minimal implementation for features only for now.
**NOTE** It's just a plain service for now, likely we'll want to allow setting this by the consuming app through config to make life easier, but we can do that later
=> Add support for new design language

addon/templates/components/polaris-popover.hbs, addon/templates/components/polaris-popover/content.hbs, config/ember-try.js, package.json, yarn.lock
Updates `ember-basic-dropdown` to the most recent release (v3.0.11) with the aim of fixing a build error being seen in other `ember-polaris` PRs. The breaking changes involved in this update can be found in the [`ember-basic-dropdown` release notes](https://github.com/cibernox/ember-basic-dropdown/releases/tag/v2.0.0-alpha.1).
=> Update ember-basic-dropdown to latest release

addon/templates/components/polaris-page/header/action-group.hbs
The polaris action group didn't pass an `onAction` to the underlying `PolarisPage::Action` component and was relying on event bubbling for the popover's activator to work. With some recent changes to stop event propagation in that component, this stopped working. So this PR adds an implicit `onAction` parameter so that we don't run into any surprises in the future.
Testing: verified that the functionality was broken on master by looking at the dummy app & validated that it works as expected with this change.
=> Explicitly pass action to polaris page action

addon/components/polaris-text-field.js
Removes our previous usage of `getCode` from `ember-keyboard` in the `PolarisTextField` component to prevent an error being thrown when typing values into numeric text fields.
=> Remove usage of deprecated getCode function from ember-keyboard

addon/helpers/is-component-definition.js, tests/integration/helpers/is-component-definition-test.js
At some point, component definitions in production switched to using Symbol keys instead of string keys. This broke our `is-component-definition` helper, which resulted in some breakages elsewhere. This PR adds a rudimentary check for these new-style component definitions.
This is at least the second time that this helper has broken as a result of Ember/Glimmer updates. I'm aware that we should be trying to figure out a way to remove it or make it less brittle/dependent on internals, but for the time being I think this workaround will have to do 😅 
Demo of something now working after this change that was previously broken (the strong part of the help text was previously not updating because it was not receiving updates due to `is-component-definition` returning a false negative):
=> Fix broken Glimmer component detection

addon/helpers/is-component-definition.js
This is the result of a conversation [here](https://github.com/smile-io/ember-polaris/pull/704/files#r585980715) where I fixed failing tests for `ember try:one ember-release` for Ember 3.25.1 in a renovate bot PR. We decided to PR this fix separately so it was easier to track.
=> Update is-component-definition for ember update

addon/components/polaris-color-picker/slidable.js, addon/components/polaris-drop-zone.js, addon/components/polaris-popover.js, addon/components/polaris-sticky.js, addon/services/sticky-manager.js, addon/utils/geometry.js, app/utils/geometry.js, package.json, tests/integration/components/polaris-color-picker-test.js, yarn.lock
As chatted, we're changing the target for the upgrade that's in progress from `polaris-react` `v5.5` -> `v6.6`.
- updates Shopify deps to 6.6
- adds directly a port of `geometry.js` instead of relying on `@shopify/javascript-utilities` dependency, following Shopify
=> Change upgrade target to Shopify 6.6 version

.github/workflows/ci.yml, docs/resource-list.md
According to [this issue](https://github.com/smile-io/engineering/issues/10), this pull request removes the master branch reference from the config file and updates the URLs of repositories that are already using main.
=> Rename master to main

README.md
This info about changelog generation was buried deep in our Slack and seemed worth adding to the README before it gets "expired".
=> Add changelog generator note to README

.github/CODEOWNERS
[Jira ticket
](https://smileio.atlassian.net/browse/PROD-3931?atlOrigin=eyJpIjoiMWNkY2ZlZjM1Y2RmNDRlMzk5MzY0ZDhlYzEyOGFjNmYiLCJwIjoiaiJ9)
Merchant squad is the maintainer of this repository and this PR is adding github's CODEOWNERS to reflect this.
=> Add merchant squad as code owners
