README.md

Ensures component documentation links are always relative

Fix component documentation links

---

.travis.yml
index.js
package.json
yarn.lock

Needs some testing in apps, tests pass locally but not on Travis...will check

Depedencies and tweaks

---

index.js

Adding this to ease development/debugging

Add is developing addon based on flag

---

addon/components/polaris-text-field.js

Noticed this function while browsing through this component for a different effort.

Fix broken function required by polaris text field

---

CHANGELOG.md
addon/components/polaris-button.js
addon/templates/components/polaris-button.hbs
tests/integration/components/polaris-button-test.js

Finishes https://github.com/smile-io/ember-polaris/issues/180
Diff [here](https://github.com/Shopify/polaris/compare/v2.2.0...v2.11.0?diff=split#diff-80ce11d837170156710fe9e24d078a78)
FYI I ran the `qunit-dom-codemod` on the test file here, so it'll be a lot easier to review the new test by just looking at this commit [here](https://github.com/smile-io/ember-polaris/pull/185/commits/9eadcbe4a7114f4be0ff4bbc1f9c757c279de09f?utf8=%E2%9C%93&diff=unified)

Upgrade polaris-button component

---

addon/components/polaris-form-layout.js
addon/components/polaris-form-layout/group.js
addon/components/polaris-form-layout/item.js
addon/templates/components/polaris-form-layout/group.hbs
addon/utils/id.js
tests/integration/components/polaris-form-layout-test.js

fix #200 
Diff [here](https://github.com/Shopify/polaris/compare/v2.2.0...v2.11.0#diff-2c66129801b5f27907be29599dfc4cd9R2)

Update polaris-form-layout component

---

addon/components/polaris-progress-bar.js
addon/templates/components/polaris-progress-bar.hbs
tests/integration/components/polaris-progress-bar-test.js

fixes #206
Diff [here](https://github.com/Shopify/polaris/compare/v2.2.0...v2.11.0#diff-5b3d58981d40a451fed5f963ee40508cR3)

Update progress-bar component

---

addon/components/polaris-labelled.js
addon/components/polaris-range-slider.js
addon/templates/components/polaris-labelled.hbs
addon/templates/components/polaris-range-slider.hbs
tests/integration/components/polaris-range-slider-test.js

fixes #208 
Diff [here](https://github.com/Shopify/polaris/compare/v2.2.0...v2.11.0#diff-98bfa4b23aac9d57da544e765d5fed58R7)

Update range-slider component

---

addon/components/polaris-text-style.js
addon/templates/components/polaris-text-style.hbs
tests/integration/components/polaris-text-style-test.js

fix #210
Diff [here](https://github.com/Shopify/polaris/compare/v2.2.0...v2.11.0#diff-66a7abb8f39a28e40bea8a08b2609fb4R5)

Update text-style component

---

CHANGELOG.md
addon/components/polaris-empty-state.js
addon/components/polaris-empty-state/details.js
addon/templates/components/polaris-empty-state.hbs
addon/templates/components/polaris-empty-state/details.hbs
tests/integration/components/polaris-empty-state-test.js

Update empty state to v2.11.0

---

CHANGELOG.md
addon/templates/components/polaris-radio-button.hbs
tests/integration/components/polaris-radio-button-test.js

Diff [here](https://github.com/Shopify/polaris/compare/v2.2.0...v2.11.0#diff-c8fd35a0b10ec3c24926318011c0ae40)
Finishes https://github.com/smile-io/ember-polaris/issues/220

Upgrade v2.11.0 radio button

---

CHANGELOG.md
addon/components/polaris-connected.js
addon/components/polaris-text-field.js
addon/components/polaris-text-field/resizer.js
addon/templates/components/polaris-connected.hbs
addon/templates/components/polaris-label.hbs
addon/templates/components/polaris-labelled.hbs
addon/templates/components/polaris-text-field.hbs
addon/templates/components/polaris-text-field/spinner.hbs
tests/integration/components/polaris-text-field-test.js

fixes #212
Diff [here](https://github.com/Shopify/polaris/compare/v2.2.0...v2.11.0#diff-ce1bd24f5c7c2bd4b9fb5d55a5aa97aeR6)

Update text-field component

---

CHANGELOG.md
addon/components/polaris-action-list/item.js
addon/templates/components/polaris-action-list/item.hbs
tests/integration/components/polaris-action-list-test.js

Diff [here](https://github.com/Shopify/polaris/compare/v2.2.0...v2.11.0#diff-14cf722ae232abc5bf49b2834f36df69)
Finishes https://github.com/smile-io/ember-polaris/issues/231

Upgrade v2.11.0 action list item

---

addon/templates/components/polaris-select.hbs
tests/integration/components/polaris-select-test.js

Fixes https://github.com/smile-io/ember-polaris/issues/242

Bugfix polaris-select wrong selected option on init

---

addon/components/polaris-badge.js

Adds the new `size` attribute. I haven't updated tests here since there aren't any for this in `polaris-react`, but happy to add one if you guys think there's value to it.

Update badge to Polaris v3.10.0

---

addon/components/polaris-callout-card.js
addon/templates/components/polaris-callout-card.hbs
tests/integration/components/polaris-callout-card-test.js

Adds support for `onDismiss` to make `polaris-callout-card` dismissable.

Update callout card to Polaris v3.10.0

---

addon/components/polaris-choice.js

BIG CHANGES ALERT! jk, I diffed the React version against the wrong revision and thought there were some real changes to make, then by the time I realised I'd already updated these and thought we may as well keep 'em 🤷‍♂️

Update choice property descriptions

---

addon/components/polaris-checkbox.js
addon/templates/components/polaris-checkbox.hbs
tests/integration/components/polaris-checkbox-test.js

Updates `polaris-checkbox` error handling and adds focus fix as per the React implementation. Also updates the tests to match those found in the React implementation.

Update checkbox to Polaris v3.10.0

---

addon/components/polaris-layout/section.js
tests/integration/components/polaris-layout-test.js

Adds `oneHalf` and `oneThird` options to `polaris-layout/section`.

Update layout to v3.10.0

---

addon/components/polaris-popover/content.js
config/ember-try.js

Fixes what's seen in the recording below,

Stop popover content from jumping around

---

addon/components/polaris-card.js
addon/components/polaris-card/section-header.js
addon/components/polaris-card/section.js
addon/templates/components/polaris-card.hbs
addon/templates/components/polaris-card/section-header.hbs
addon/templates/components/polaris-card/section.hbs
tests/dummy/config/deprecation-workflow.js

Refactor polaris-card

---

addon/components/polaris-visually-hidden.js
addon/templates/components/polaris-visually-hidden.hbs
tests/integration/components/polaris-visually-hidden-test.js

Refactor polaris-visually-hidden component

---

addon/components/polaris-thumbnail.js
addon/templates/components/polaris-thumbnail.hbs

Refactor polaris-thumbnail component

---

addon/components/polaris-page.js
addon/components/polaris-page/action-icon.js
addon/components/polaris-page/action.js
addon/components/polaris-page/header.js
addon/components/polaris-page/header/action-group.js
addon/components/polaris-page/header/rollup.js
addon/templates/components/polaris-page.hbs
addon/templates/components/polaris-page/action-icon.hbs
addon/templates/components/polaris-page/action.hbs
addon/templates/components/polaris-page/header.hbs
addon/templates/components/polaris-page/header/action-group.hbs
addon/templates/components/polaris-page/header/rollup.hbs
package.json
tests/integration/components/polaris-page-test.js
yarn.lock

Refactor  polaris-page

---

addon/components/polaris-unstyled-link.js
addon/templates/components/polaris-breadcrumbs.hbs
addon/templates/components/polaris-button.hbs
addon/templates/components/polaris-link.hbs
addon/templates/components/polaris-resource-list/bulk-actions/bulk-action-button.hbs
addon/templates/components/polaris-resource-list/item.hbs
addon/templates/components/polaris-unstyled-link.hbs
tests/integration/components/polaris-button-test.js
tests/integration/components/polaris-unstyled-link-test.js

Refactor polaris-unstyled-link component

---

addon/components/polaris-avatar.js
addon/templates/components/polaris-avatar.hbs
package.json
tests/integration/components/polaris-avatar-test.js
yarn.lock

Refactor polaris-avatar component

---

addon/components/polaris-banner.js
tests/integration/components/polaris-banner-test.js

Fixes triggering the Banner's main action

Fix banner primary action
